### ISSUE TITLE
classic wotlk: All calls to CreateAnimation("Scale") results in nil

### ISSUE THREAD

**Issue by andmer** [rgd87/NugKeyFeedback#1]
All calls to CreateAnimation("Scale") results in nil on WOTLK classic

**Comment by andmer** [comment]
this version works: https://github.com/rgd87/NugKeyFeedback/blob/9acf83229c39decd254d86b37b4659da5101f993/Frame.lua

**Comment by d87** [comment]
Thanks, fixed in 10.0.1
